### ISSUE TITLE
Wrong date timestamp for checkin output

### ISSUE THREAD

**Issue by bhahn1800** [altodd/Southwest-Docker#2]
Hi - my flight is departing IND at 5am on 2022-04-01

The output says it will start the cron job to checkin at 'Thu Mar 31 10:00:00 2022'

Shouldn't this be 'Thu Mar 31 5:00:00 2022' given that my flight leaves the next day at 5am?

![image](https://user-images.githubusercontent.com/9807451/157913460-0ec07014-896b-47c4-9833-80911e50f261.png)

**Comment by altodd** [comment]
I just wrote the docker container, the ruby gem by alextran is what is doing the scheduling - that said, what it looks like to me is that the cron job is scheduled with universal (zulu) time. It shows flight departing at 05:00 in the message above and 0500 eastern is 1000z. I haven't had any issues with scheduling the check-ins so far but haven't paid too much attention to the job timestamps. It may also just be the timezone of the container  - I don't believe this is an issue from what I see, but can try to verify the difference if I get time.

**Comment by bhahn1800** [comment]
thanks!  I'll see what happens for this particular check-in here in a few weeks
