### ISSUE TITLE
where does the email go?  and autoluv log file

### ISSUE THREAD

**Issue by hildebrau** [altodd/Southwest-Docker#4]
When we schedule a job, we give it an email address.

When the at job fires off, I see /var/log/exim4/mainlog shows a mail was sent.. but where does it go?  I never receive it at the address I scheduled with.

root@aa599a5e9601:/var/log/exim4# cat mainlog 
2022-09-07 14:35:20 1oVw9A-00008C-G3 <= root@bfdb1f6222b3 U=root P=local S=390
2022-09-07 14:35:20 1oVw9A-00008C-G3 => /var/mail/mail <root@bfdb1f6222b3> R=mail4root T=address_file
2022-09-07 14:35:20 1oVw9A-00008C-G3 Completed

On a similar note, is there some local log file that I can review to see how successful or unsuccessful the autoluv process was at checking in?

**Comment by hildebrau** [comment]
I also found this file.

root@aa599a5e9601:/var/log/exim4# cat /var/mail/mail
From root@bfdb1f6222b3 Wed Sep 07 14:35:20 2022
Return-path: <root@bfdb1f6222b3>
Envelope-to: root@bfdb1f6222b3
Delivery-date: Wed, 07 Sep 2022 14:35:20 +0000
Received: from root by aa599a5e9601 with local (Exim 4.94.2)
        (envelope-from <root@bfdb1f6222b3>)
        id 1oVw9A-00008C-G3
        for root@bfdb1f6222b3; Wed, 07 Sep 2022 14:35:20 +0000
Subject: Output from your job        1
To: root@bfdb1f6222b3
Message-Id: <E1oVw9A-00008C-G3@aa599a5e9601>
From: root <root@bfdb1f6222b3>
Date: Wed, 07 Sep 2022 14:35:20 +0000

535 Authentication credentials invalid

**Comment by hildebrau** [comment]
With the power of "find", I discovered this log.  I sanitized the filename a bit. 
I see some errors in here.. but I suspect the check in actually worked, as when I went to do it manually, it seemed like it was already done.  But I can't be sure the other person didn't manually check in as well.  I sort of expected to see output showing Success!  Your boarding group is B28 or whatever.

cat /var/lib/gems/2.7.0/gems/autoluv-0.3.1/logs/First\ Last/PNRCODE.log 
# Logfile created on 2022-09-07 14:35:19 +0000 by logger.rb/v1.4.2
E, [2022-09-07T14:35:19.885551 #510] ERROR -- : Error.
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
/usr/lib/ruby/2.7.0/net/http.rb:933:in `start'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
/var/lib/gems/2.7.0/gems/autoluv-0.3.1/lib/autoluv/southwestclient.rb:48:in `block in check_in'
/var/lib/gems/2.7.0/gems/autoluv-0.3.1/lib/autoluv/southwestclient.rb:44:in `times'
/var/lib/gems/2.7.0/gems/autoluv-0.3.1/lib/autoluv/southwestclient.rb:44:in `check_in'
/var/lib/gems/2.7.0/gems/autoluv-0.3.1/bin/autoluv:21:in `<top (required)>'
/usr/local/bin/autoluv:23:in `load'
/usr/local/bin/autoluv:23:in `<main>'

**Comment by altodd** [comment]
Per what I said in #5 I am doing some testing on a new image - this is just a container for alextrans work and he recently pushed a fix for chromedriver. Email was having some issues with authentication - I believe the provider flagged the account, I will be trying a new config and will have to leave configuration up to the user if there are issues this way. Leaving this ticket open to track testing of the image.

**Comment by hildebrau** [comment]
Oh. I see. It would be no problem if I had to specify my own mail server credentials in a variable or whatnot. Is there a way to specify that already?

**Comment by altodd** [comment]
I just pushed an updated image to docker hub, I just checked the wife in successfully and got an email. If you want to build the image itself though in the repo is the .autoluv.env file with the current credentials that no longer work, you can replace that with your own smtp credentials as described [https://github.com/byalextran/southwest-checkin#get-southwest-headers](here) and mount that into the container (haven't tested that, not sure if the gem need re-installed after making that) or re-build the image
