### ISSUE TITLE
Can't send email - 535 Authentication credentials invalid

### ISSUE THREAD

**Issue by dazayas** [altodd/Southwest-Docker#5]
When using the email option, the following is output:

`dazayas@xxxxxx:~$ docker run -it altodd/southwest-docker checkin xxxxxx yyyyyy zzzzzz xxxxxx@xxxxxx.com`
`Starting deferred execution scheduler: atd.`
`Starting periodic command scheduler: cron.`
`535 Authentication credentials invalid`

If no email is input, the script seems to work correctly (e.g. points out that it's more than 24 hours until the flight).  I did log into the container and verify the .autoluv.env file is present and seems correctly formatted.

**Comment by altodd** [comment]
Closing this as there is more info on #4 with similar questions. (Sorry for the extremely slow response, haven't done much on Git Hub lately). Ultimately the email stopped working after a couple months for me - I think the provider flagged the account. I am planning to do some testing with a new email service and alextran's fixes for chromedriver and will push an updated image if that works. If the image still has issues with email I may just have to let people use their own email service - was trying to make it easier to not have to configure.
